### ISSUE TITLE
Function to call REST API to fetch all forms' initial data

### ISSUE THREAD

**Issue by pingpingsim** [django/django-formtools#133]
I am making use of the formtool wizard form to let users save and update the registration info. All input data will be saved and stored on the server.
During the wizard onload, I would like to make a single REST API call to fetch all the initial data for the forms in the wizard. Is there an init or onload function for the wizard which applies to the whole wizard, the loaded initial data will be stored in the session and will be applied as the initial data of each form accordingly. There're helper functions such as get_form_initial, get_form etc but they only caters to single step. Please advise on this.

**Comment by claudep** [comment]
I'm afraid you are using the wrong channel to get support. You might have more success using other Django support channels: https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels
