### ISSUE TITLE
Random test failure: TestCookieStorage.test_reset_cookie

### ISSUE THREAD

**Issue by timgraham** [django/django-formtools#30]
Originally reported in [#23792](https://code.djangoproject.com/ticket/23792). Should we use the `freeze_time()` contextmanager proposed there? If so, it seems we'll have to drop compatibility with Django 1.7.

**Comment by gchp** [comment]
@timgraham @jezdez Is this still an issue? I don't see anywhere in the formtools tests that could use the freeze_time context manager. I also don't see any failing tests and the link inside the trac issue is broken so I can't see what test was failing originally.

**Comment by timgraham** [comment]
I don't think anything has been done to fix it, but I don't mind if you close this until the next time the failure happens.

**Comment by gchp** [comment]
Cheers @timgraham. I'll close for now, and re-open should it crop up again.
