### ISSUE TITLE
Some of the files submitted using formsets are missing

### ISSUE THREAD

**Issue by gitfred** [django/django-formtools#42]
Occured when using formset which contains few instances of the same form class (with file fields) in a single step.
It's caused by `MultiValueDict.__getitem__` method which returns only last element of values list:
https://github.com/django/django/blob/master/django/utils/datastructures.py#L84

For example:
In one single step we have 3 instances of form which contains file field - and only the file from last step is saved when using `form_dict['our_step'].save()` method. That means the files submitted in the first 2 forms are lost forever, which is IMO not desired behaviour by default.

As a workaround we can override `get_form_step_files()` method and extract all files one by one using `MultiValueDict`'s `getlist` method:
```python
    def get_form_step_files(self, form):
        ret = {}
        for key in form.files.keys():
            for i, file_ in enumerate(form.files.getlist(key)):
                ret["{}-{}".format(key, i)] = file_

        return ret
```
And then save it properly in `done()` method:
```python
        formset = form_dict['our_step']
        for i, form in enumerate(formset):
            form.instance.avatar = formset.files[
                "{}-{}-{}".format('our_step', 'avatar', i)]

            form.instance.family = formset.files[
                "{}-{}-{}".format('our_step', 'family', i)]

            form.save()
```

**Comment by eriktelepovsky** [comment]
Thank you @gitfred for this. I was working on support for handling multiple file input fields and this helped me a lot.
