### ISSUE TITLE
Make PyPI release

### ISSUE THREAD

**Issue by jezdez** [django/django-formtools#5]

**Comment by jannh** [comment]
Is there any progress on this issue? Django 1.8 is approaching fast and I guess it is important for a lot of people to have a PyPI - package with the formtools...

**Comment by timgraham** [comment]
@jezdez will try to do it this week.

**Comment by jezdez** [comment]
Actually this week, sorry for the delay.

**Comment by thedrow** [comment]
@jezdez 1.0.0 is [released](https://pypi.python.org/pypi/django-formtools). Should this issue be closed?

**Comment by jezdez** [comment]
Ah, yeah.
