### ISSUE TITLE
remove the Django>=1.7 dependency in setup.py

### ISSUE THREAD

**Issue by stefanfoulis** [django/django-formtools#52]
Obviously only if the package actually works with Django 1.6.

The reason being that we maintain a package that still supports Django 1.6 (django-cms 3.2.x). So for 1.7+ we add a dependency to django-formtools. Unfortunately it is not possible to conditionally install a dependency, only if a certain version of a other package is present. So even if our package is used in a Django 1.6.x Project we still have to install django-formtools. This is especially a problem with strict dependency checkers like pip-tools.

Thus we'd like to use django-formtools for Django 1.6.x, even if we could also use the builtin version.

**Comment by timgraham** [comment]
Sorry, but I don't think we're going to spend any time testing the package with Django 1.6 which is obsolete by now.
