### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by holyoaks** [django/django-formtools#55]
I asked this at https://groups.google.com/forum/#!searchin/django-users/formtools/django-users/YA4x3qQPGQA/WNkLWVPQCAAJ but never received an answer. I don't know if this is the right place to ask this, but here goes.

I'm wondering if I can use django-formtools to accomplish what I want to. I have a License object, with a one to many relationship to LicenseArea. The number of LicenseArea objects varies for each license, so I would like a wizard that has:

Step 0 - the license data
Step 1 - the common data for all LicenseArea objects
Step 2-through n - The same form for each LicenseArea to enter the unique data for each LicenseArea

I've currently implemented this as two steps, one for the License, and then a Formset for each LicenseArea, but as the amount of data for each LicenseArea is significant, the UI leaves a great deal to be desired. I was thinking one step for each LicenseArea would work better. Is this possible, and if so, how best would I implement this? Thanks.

**Comment by timgraham** [comment]
No, this is a bug tracker not a support channel.
