### ISSUE TITLE
WizardView.done() uses render_to_response() which might get deprecated in the future

### ISSUE THREAD

**Issue by sevesalm** [django/django-formtools#59]
WizardView.done() uses the function render_to_response(), instead of the newer render() function:

https://docs.djangoproject.com/en/1.9/topics/http/shortcuts/#render
https://docs.djangoproject.com/en/1.9/topics/http/shortcuts/#render-to-response

> This function [render_to_response()] preceded the introduction of render() and works similarly except that it doesn’t make the request available in the response. It’s not recommended and is likely to be deprecated in the future.

Not presently a show stopper but might be in the future.

**Comment by claudep** [comment]
Thanks for the report, fixed in 46b6839fb0063fa10ffb896ce80f7155ca7a9f6e
